apiVersion: apps/v1
kind: Deployment
metadata:
  name: producer-kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: producer-kafka
  template:
    metadata:
      labels:
        app: producer-kafka
    spec:
      containers:
      - name: producer-kafka
        image: gcr.io/pgt-beans/us-central1/producer-kafka:latest
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 250m
            memory: 750Mi
          limits:
            cpu: 500m
            memory: 1400Mi
